import type { Product } from './types'

// Drop a photo in src/assets/products, run `npm run optimize:images`, then reference it here by filename (no extension).
const optimizedImages = import.meta.glob('../assets/optimized/*.webp', { eager: true, import: 'default' }) as Record<string, string>
const productImages = Object.fromEntries(Object.entries(optimizedImages).map(([filePath, url]) => [filePath.split('/').pop()!.replace(/\.webp$/, ''), url]))
const image = (slug: string) => {
  const url = productImages[slug]
  if (!url) throw new Error(`Missing optimized product image "${slug}.webp". Run npm run optimize:images after adding it to src/assets/products.`)
  return url
}

export const seedProducts: Product[] = [
  { id: 1, sku: 'ZL-NK-001', name: 'Kundan Petal Set', category: 'Necklaces', collection: '1 Gram Jewellery', image: image('kundan-petal-set'), note: 'A delicate occasion set with ruby-toned accents and pearl drops.', finish: 'Gold-tone finish', material: 'Confirm composition before purchase', dimensions: 'Confirm sizing before purchase', weight: 'Confirm weight before purchase', colours: ['Ruby', 'Gold', 'Pearl'], occasions: ['Wedding', 'Festive'], availability: 'Confirm availability', badge: 'Signature', featured: true },
  { id: 2, sku: 'ZL-NK-002', name: 'Emerald Arc Set', category: 'Necklaces', collection: '1 Gram Jewellery', image: image('emerald-arc-set'), note: 'A sculpted silver-tone necklace with emerald-colour stones.', finish: 'Dual-tone finish', material: 'Confirm composition before purchase', dimensions: 'Confirm sizing before purchase', weight: 'Confirm weight before purchase', colours: ['Emerald', 'Silver'], occasions: ['Celebration', 'Evening'], availability: 'Confirm availability', badge: 'New', featured: true },
  { id: 3, sku: 'ZL-BR-001', name: 'Noir Clover Stack', category: 'Bracelets', collection: 'Anti Tarnish Collection', image: image('noir-clover-stack'), note: 'A mix-and-match bracelet edit for contemporary dressing.', finish: 'Anti-tarnish finish', material: 'Confirm composition before purchase', dimensions: 'Confirm fit before purchase', weight: 'Confirm weight before purchase', colours: ['Black', 'Gold'], occasions: ['Everyday', 'Gifting'], availability: 'Confirm availability', featured: true },
  { id: 4, sku: 'ZL-RG-001', name: 'Celestial Stone Rings', category: 'Rings', collection: 'CZ Collection', image: image('celestial-stone-rings'), note: 'Statement rings with varied silhouettes and crystal detailing.', finish: 'Mixed finish', material: 'Confirm composition before purchase', dimensions: 'Confirm ring sizes before purchase', weight: 'Confirm weight before purchase', colours: ['Mixed'], occasions: ['Evening', 'Gifting'], availability: 'Confirm availability' },
  { id: 5, sku: 'ZL-BG-001', name: 'Kashmiri Heritage Bangles', category: 'Bangles', collection: 'Curated Jewellery', image: image('kashmiri-heritage-bangles'), note: 'Ornate bangles inspired by traditional carved motifs.', finish: 'Antique gold-tone', material: 'Confirm composition before purchase', dimensions: 'Confirm bangle sizes before purchase', weight: 'Confirm weight before purchase', colours: ['Antique Gold'], occasions: ['Wedding', 'Festive'], availability: 'Confirm availability', badge: 'Heritage' },
  { id: 6, sku: 'ZL-NK-003', name: 'Three-Layer Celebration Set', category: 'Necklaces', collection: '1 Gram Jewellery', image: image('three-layer-celebration-set'), note: 'A layered composition designed for festive and bridal styling.', finish: 'Gold-tone finish', material: 'Confirm composition before purchase', dimensions: 'Confirm sizing before purchase', weight: 'Confirm weight before purchase', colours: ['Gold', 'Ruby'], occasions: ['Wedding', 'Festive'], availability: 'Confirm availability' },
  { id: 7, sku: 'ZL-NK-004', name: 'Butterfly Bead Chain', category: 'Necklaces', collection: 'Mangalsutras', image: image('butterfly-bead-chain'), note: 'A light black-bead chain finished with a playful butterfly motif.', finish: 'Gold-tone finish', material: 'Confirm composition before purchase', dimensions: 'Confirm length before purchase', weight: 'Confirm weight before purchase', colours: ['Black', 'Gold'], occasions: ['Everyday', 'Gifting'], availability: 'Confirm availability' },
  { id: 8, sku: 'ZL-NK-005', name: 'Panchaloham Occasion Set', category: 'Necklaces', collection: 'Panchaloham Jewellery', image: image('panchaloham-occasion-set'), note: 'A richly detailed set for traditional occasion dressing.', finish: 'Five-metal inspired finish', material: 'Confirm composition before purchase', dimensions: 'Confirm sizing before purchase', weight: 'Confirm weight before purchase', colours: ['Mixed Metal'], occasions: ['Wedding', 'Festive'], availability: 'Confirm availability' },
]