import heroImage from '../assets/optimized/kundan-petal-set.webp'
import greenSet from '../assets/optimized/emerald-arc-set.webp'
import bracelets from '../assets/optimized/noir-clover-stack.webp'
import stoneRings from '../assets/optimized/celestial-stone-rings.webp'
import kashmiriBangles from '../assets/optimized/kashmiri-heritage-bangles.webp'
import layerSet from '../assets/optimized/three-layer-celebration-set.webp'
import butterflyChain from '../assets/optimized/butterfly-bead-chain.webp'
import panchalohamSet from '../assets/optimized/panchaloham-occasion-set.webp'
import type { Product } from './types'

export const seedProducts: Product[] = [
  { id: 1, sku: 'ZL-NK-001', name: 'Kundan Petal Set', category: 'Necklaces', collection: '1 Gram Jewellery', image: heroImage, note: 'A delicate occasion set with ruby-toned accents and pearl drops.', finish: 'Gold-tone finish', material: 'Confirm composition before purchase', dimensions: 'Confirm sizing before purchase', weight: 'Confirm weight before purchase', colours: ['Ruby', 'Gold', 'Pearl'], occasions: ['Wedding', 'Festive'], availability: 'Confirm availability', badge: 'Signature', featured: true },
  { id: 2, sku: 'ZL-NK-002', name: 'Emerald Arc Set', category: 'Necklaces', collection: '1 Gram Jewellery', image: greenSet, note: 'A sculpted silver-tone necklace with emerald-colour stones.', finish: 'Dual-tone finish', material: 'Confirm composition before purchase', dimensions: 'Confirm sizing before purchase', weight: 'Confirm weight before purchase', colours: ['Emerald', 'Silver'], occasions: ['Celebration', 'Evening'], availability: 'Confirm availability', badge: 'New', featured: true },
  { id: 3, sku: 'ZL-BR-001', name: 'Noir Clover Stack', category: 'Bracelets', collection: 'Anti Tarnish Collection', image: bracelets, note: 'A mix-and-match bracelet edit for contemporary dressing.', finish: 'Anti-tarnish finish', material: 'Confirm composition before purchase', dimensions: 'Confirm fit before purchase', weight: 'Confirm weight before purchase', colours: ['Black', 'Gold'], occasions: ['Everyday', 'Gifting'], availability: 'Confirm availability', featured: true },
  { id: 4, sku: 'ZL-RG-001', name: 'Celestial Stone Rings', category: 'Rings', collection: 'CZ Collection', image: stoneRings, note: 'Statement rings with varied silhouettes and crystal detailing.', finish: 'Mixed finish', material: 'Confirm composition before purchase', dimensions: 'Confirm ring sizes before purchase', weight: 'Confirm weight before purchase', colours: ['Mixed'], occasions: ['Evening', 'Gifting'], availability: 'Confirm availability' },
  { id: 5, sku: 'ZL-BG-001', name: 'Kashmiri Heritage Bangles', category: 'Bangles', collection: 'Curated Jewellery', image: kashmiriBangles, note: 'Ornate bangles inspired by traditional carved motifs.', finish: 'Antique gold-tone', material: 'Confirm composition before purchase', dimensions: 'Confirm bangle sizes before purchase', weight: 'Confirm weight before purchase', colours: ['Antique Gold'], occasions: ['Wedding', 'Festive'], availability: 'Confirm availability', badge: 'Heritage' },
  { id: 6, sku: 'ZL-NK-003', name: 'Three-Layer Celebration Set', category: 'Necklaces', collection: '1 Gram Jewellery', image: layerSet, note: 'A layered composition designed for festive and bridal styling.', finish: 'Gold-tone finish', material: 'Confirm composition before purchase', dimensions: 'Confirm sizing before purchase', weight: 'Confirm weight before purchase', colours: ['Gold', 'Ruby'], occasions: ['Wedding', 'Festive'], availability: 'Confirm availability' },
  { id: 7, sku: 'ZL-NK-004', name: 'Butterfly Bead Chain', category: 'Necklaces', collection: 'Mangalsutras', image: butterflyChain, note: 'A light black-bead chain finished with a playful butterfly motif.', finish: 'Gold-tone finish', material: 'Confirm composition before purchase', dimensions: 'Confirm length before purchase', weight: 'Confirm weight before purchase', colours: ['Black', 'Gold'], occasions: ['Everyday', 'Gifting'], availability: 'Confirm availability' },
  { id: 8, sku: 'ZL-NK-005', name: 'Panchaloham Occasion Set', category: 'Necklaces', collection: 'Panchaloham Jewellery', image: panchalohamSet, note: 'A richly detailed set for traditional occasion dressing.', finish: 'Five-metal inspired finish', material: 'Confirm composition before purchase', dimensions: 'Confirm sizing before purchase', weight: 'Confirm weight before purchase', colours: ['Mixed Metal'], occasions: ['Wedding', 'Festive'], availability: 'Confirm availability' },
]