create extension if not exists pgcrypto;

create table public.catalog_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.collections (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  display_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  sku text not null unique check (length(trim(sku)) > 0),
  name text not null check (length(trim(name)) > 0),
  category_id uuid not null references public.categories(id),
  note text not null default '',
  material text,
  finish text,
  dimensions text,
  weight text,
  weight_grams numeric(10, 3) check (weight_grams is null or weight_grams > 0),
  length_mm numeric(10, 2) check (length_mm is null or length_mm > 0),
  width_mm numeric(10, 2) check (width_mm is null or width_mm > 0),
  height_mm numeric(10, 2) check (height_mm is null or height_mm > 0),
  size_notes text,
  colours text[] not null default '{}',
  occasions text[] not null default '{}',
  stock_quantity integer check (stock_quantity is null or stock_quantity >= 0),
  low_stock_level integer not null default 2 check (low_stock_level >= 0),
  track_stock boolean not null default false,
  badge text,
  featured boolean not null default false,
  display_order integer not null default 0,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_collections (
  product_id bigint not null references public.products(id) on delete cascade,
  collection_id uuid not null references public.collections(id) on delete cascade,
  is_primary boolean not null default false,
  primary key (product_id, collection_id)
);

create unique index product_collections_one_primary
  on public.product_collections (product_id)
  where is_primary;

create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  url text not null check (length(trim(url)) > 0),
  alt_text text not null default '',
  image_type text not null default 'front' check (image_type in ('front', 'back', 'detail', 'model', 'variant', 'packaging')),
  display_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

create unique index product_images_one_primary
  on public.product_images (product_id)
  where is_primary;

create table public.product_prices (
  product_id bigint primary key references public.products(id) on delete cascade,
  regular_price_paise integer check (regular_price_paise is null or regular_price_paise >= 0),
  sale_price_paise integer,
  sale_starts_at timestamptz,
  sale_ends_at timestamptz,
  updated_at timestamptz not null default now(),
  check (sale_price_paise is null or regular_price_paise is not null),
  check (sale_price_paise is null or sale_price_paise >= 0),
  check (sale_price_paise is null or sale_price_paise < regular_price_paise),
  check (sale_ends_at is null or sale_starts_at is null or sale_ends_at > sale_starts_at)
);

create table public.inventory_transactions (
  id bigint generated always as identity primary key,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity_change integer not null check (quantity_change <> 0),
  quantity_after integer not null check (quantity_after >= 0),
  reason text not null check (reason in ('received', 'sale', 'damage', 'return', 'correction')),
  notes text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create index products_category_id_idx on public.products(category_id);
create index products_status_idx on public.products(status);
create index inventory_transactions_product_id_created_at_idx
  on public.inventory_transactions(product_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger categories_set_updated_at before update on public.categories
for each row execute function public.set_updated_at();
create trigger collections_set_updated_at before update on public.collections
for each row execute function public.set_updated_at();
create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();
create trigger product_prices_set_updated_at before update on public.product_prices
for each row execute function public.set_updated_at();

create or replace function public.is_catalog_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.catalog_admins where user_id = auth.uid()
  );
$$;

create or replace function public.adjust_inventory(
  target_product_id bigint,
  quantity_change integer,
  adjustment_reason text,
  adjustment_notes text default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  next_quantity integer;
begin
  if not public.is_catalog_admin() then
    raise exception 'Catalogue administrator access required';
  end if;
  if quantity_change = 0 then
    raise exception 'Quantity change cannot be zero';
  end if;
  if adjustment_reason not in ('received', 'sale', 'damage', 'return', 'correction') then
    raise exception 'Invalid inventory adjustment reason';
  end if;

  update public.products
  set stock_quantity = coalesce(stock_quantity, 0) + quantity_change,
      track_stock = true
  where id = target_product_id
    and coalesce(stock_quantity, 0) + quantity_change >= 0
  returning stock_quantity into next_quantity;

  if next_quantity is null then
    raise exception 'Product not found or adjustment would make stock negative';
  end if;

  insert into public.inventory_transactions (
    product_id, quantity_change, quantity_after, reason, notes, created_by
  ) values (
    target_product_id, quantity_change, next_quantity, adjustment_reason, adjustment_notes, auth.uid()
  );

  return next_quantity;
end;
$$;

create view public.storefront_catalog
with (security_invoker = true)
as
select
  p.id,
  p.sku,
  p.name,
  category.name as category,
  primary_collection.name as collection,
  p.note,
  p.finish,
  p.material,
  p.dimensions,
  p.weight,
  p.colours,
  p.occasions,
  images.image_url,
  images.image_urls,
  price.regular_price_paise,
  case
    when price.sale_price_paise is not null
      and (price.sale_starts_at is null or price.sale_starts_at <= now())
      and (price.sale_ends_at is null or price.sale_ends_at > now())
    then price.sale_price_paise
    else null
  end as sale_price_paise,
  p.stock_quantity,
  p.low_stock_level,
  p.track_stock,
  p.badge,
  p.featured,
  p.display_order
from public.products p
join public.categories category on category.id = p.category_id and category.active
join lateral (
  select collection.name
  from public.product_collections link
  join public.collections collection on collection.id = link.collection_id
  where link.product_id = p.id and link.is_primary and collection.active
  limit 1
) primary_collection on true
join lateral (
  select
    (array_agg(image.url order by image.is_primary desc, image.display_order, image.id))[1] as image_url,
    array_agg(image.url order by image.is_primary desc, image.display_order, image.id) as image_urls
  from public.product_images image
  where image.product_id = p.id
) images on images.image_url is not null
left join public.product_prices price on price.product_id = p.id
where p.status = 'published';

alter table public.catalog_admins enable row level security;
alter table public.categories enable row level security;
alter table public.collections enable row level security;
alter table public.products enable row level security;
alter table public.product_collections enable row level security;
alter table public.product_images enable row level security;
alter table public.product_prices enable row level security;
alter table public.inventory_transactions enable row level security;

create policy "Admins can view their role" on public.catalog_admins
for select to authenticated using (user_id = auth.uid());

create policy "Public can view active categories" on public.categories
for select using (active or public.is_catalog_admin());
create policy "Admins manage categories" on public.categories
for all to authenticated using (public.is_catalog_admin()) with check (public.is_catalog_admin());

create policy "Public can view active collections" on public.collections
for select using (active or public.is_catalog_admin());
create policy "Admins manage collections" on public.collections
for all to authenticated using (public.is_catalog_admin()) with check (public.is_catalog_admin());

create policy "Public can view published products" on public.products
for select using (status = 'published' or public.is_catalog_admin());
create policy "Admins manage products" on public.products
for all to authenticated using (public.is_catalog_admin()) with check (public.is_catalog_admin());

create policy "Public can view published product collections" on public.product_collections
for select using (exists (select 1 from public.products where id = product_id and status = 'published') or public.is_catalog_admin());
create policy "Admins manage product collections" on public.product_collections
for all to authenticated using (public.is_catalog_admin()) with check (public.is_catalog_admin());

create policy "Public can view published product images" on public.product_images
for select using (exists (select 1 from public.products where id = product_id and status = 'published') or public.is_catalog_admin());
create policy "Admins manage product images" on public.product_images
for all to authenticated using (public.is_catalog_admin()) with check (public.is_catalog_admin());

create policy "Public can view published product prices" on public.product_prices
for select using (exists (select 1 from public.products where id = product_id and status = 'published') or public.is_catalog_admin());
create policy "Admins manage product prices" on public.product_prices
for all to authenticated using (public.is_catalog_admin()) with check (public.is_catalog_admin());

create policy "Admins view inventory history" on public.inventory_transactions
for select to authenticated using (public.is_catalog_admin());

revoke all on function public.adjust_inventory(bigint, integer, text, text) from public;
grant execute on function public.adjust_inventory(bigint, integer, text, text) to authenticated;
grant select on public.storefront_catalog to anon, authenticated;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

create policy "Public can view product images" on storage.objects
for select using (bucket_id = 'product-images');
create policy "Admins upload product images" on storage.objects
for insert to authenticated with check (bucket_id = 'product-images' and public.is_catalog_admin());
create policy "Admins update product images" on storage.objects
for update to authenticated using (bucket_id = 'product-images' and public.is_catalog_admin())
with check (bucket_id = 'product-images' and public.is_catalog_admin());
create policy "Admins delete product images" on storage.objects
for delete to authenticated using (bucket_id = 'product-images' and public.is_catalog_admin());

insert into public.categories (name, slug, display_order) values
  ('Necklaces', 'necklaces', 10),
  ('Bangles', 'bangles', 20),
  ('Bracelets', 'bracelets', 30),
  ('Rings', 'rings', 40)
on conflict (slug) do nothing;

insert into public.collections (name, slug, display_order) values
  ('AD Jewellery', 'ad-jewellery', 10),
  ('CZ Collection', 'cz-collection', 20),
  ('1 Gram Jewellery', '1-gram-jewellery', 30),
  ('Panchaloham Jewellery', 'panchaloham-jewellery', 40),
  ('Mangalsutras', 'mangalsutras', 50),
  ('Anti Tarnish Collection', 'anti-tarnish-collection', 60),
  ('Kids Collection', 'kids-collection', 70),
  ('Curated Jewellery', 'curated-jewellery', 80)
on conflict (slug) do nothing;